config/routes.rb
Rails.application.routes.draw do
  get 'playlists/new'
  get 'playlists/create'
  get 'playlists/index'
  get 'playlists/show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :playlists, only: [:new, :create, :show, :index] do
    member do
      post "add-song"
    end
  end

  root "playlists#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  validates :title, presence: true

  has_many :songs

  def song_urls
    songs.pluck(:song_url)
  end
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :playlist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :add_song]

  def new
    @playlist = Playlist.new
    @playlists = Playlist.order(id: :desc)
  end

  def create
    @playlist = Playlist.new(title: playlist_params[:title])

    if @playlist.save
      redirect_to @playlist
    else
      render :new
    end
  end

  def index
  end

  def show
    @songs = @playlist.songs
  end

  def add_song
    url = params[:url]
    title = get_title_from_url(url)
    song = @playlist.songs.create(song_url: url, title: title)

    render(json: song)
  end

  private

  def playlist_params
    params.require(:playlist).permit(:title)
  end

  def set_playlist
    @playlist = Playlist.find(params[:id])
  end

  def youtube_id(youtube_url)
    # Found online at https://gist.github.com/niquepa/4c59b7d52a15dde2367a
    regex = /(?:youtube(?:-nocookie)?\.com\/(?:[^\/\n\s]+\/\S+\/|(?:v|e(?:mbed)?)\/|\S*?[?&]v=)|youtu\.be\/)([a-zA-Z0-9_-]{11})/
    match = regex.match(youtube_url)
    if match && !match[1].blank?
      match[1]
    else
      nil
    end
  end

  def get_title_from_url(url)
    song_id = youtube_id(url)
    Yt::Video.new(id: song_id).title
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicMondays</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src='https://unpkg.com/react-player/dist/ReactPlayer.standalone.js'></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/playlists/create.html.erb
<h1>Playlists#create</h1>
<p>Find me in app/views/playlists/create.html.erb</p>

app/views/playlists/index.html.erb
<h1>Playlists#index</h1>
<p>Find me in app/views/playlists/index.html.erb</p>

app/views/playlists/new.html.erb
<h1><div style="text-align: center;">Create Playlist</div></h1>

<div class="container">
  <div class="row">
    <div class="col-sm">
    </div>
    <div class="col-sm">
      <%= form_with model: @playlist do |form| %>
        <%= form.label :title, "Name" %>
        <%= form.text_field :title, placeholder: 'Music Monday #42'%>
        <%= form.submit %>
      <% end %>

      <% if @playlist.errors.any? %>
        <% @playlist.errors.full_messages.each do |message| %>
          <div class="danger">
            <%= message %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="col-sm">
    </div>
  </div>
</div>

<h1 class="mt-5"><div style="text-align: center;">Find a Playlist</div></h1>
<div class="container">
  <div class="row">
    <% @playlists.each do |playlist| %>
      <%= link_to playlist.title, playlist %>
    <% end %>
  </div>
</div>

app/views/playlists/show.html.erb
<h1 class="text-capitalize text-center"><%= @playlist.title %></h1>

<div class="row">
<div class="col-sm"></div>
<div class="col-sm-5">
  <div id="player-container" data-controller="playlist" data-playlist-submission-url-value="<%= add_song_playlist_path(@playlist) %>">
    <div data-playlist-target="player" class="row"></div>
    <div class="row mt-4">
      <ul data-playlist-target="songList" class="list-group" id="song-list-group">
      <% @songs.each do |song| %>
        <li
          data-playlist-target="song"
          data-action="click->playlist#play"
          data-playlist-url-param="<%= song.song_url %>"
          class="list-group-item"
        >
          <%= song.title %>
        </li>
      <% end %>
      </ul>
    </div>
    <div>
      Add Song: <input data-playlist-target="newSong"
                       type="text"
                       placeholder="Paste link here... (e.g. https://www.youtube.com/watch?v=uVi635mDYes)"
                       class="form-control"
                >
      <button id="addSongButton" class="btn btn-dark mt-2" data-action="click->playlist#addSong">Add +</button>
    </div>
  </div>
</div>
<div class="col-sm"></div>
</div>